version: '2'
services:
  web:
    build: .
    image: everton/sinatra:v2
    ports:
      - '3000:3000'
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: bundle exec thin -R config.ru start
